version: '3'

services:
  app:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
  db:
    image: mysql:5.7
    platform: linux/amd64
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  proxy:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - 8080:8080
    networks:
      - node-network

networks:
  node-network:
    driver: bridge